###

POST http://localhost:4000/lote_etiquetas/create
Content-Type: application/json

{
    "criacao":"12/11/2024",
    "semana_corte": 1,
    "semana_colheita": 13,
    "etiqueta_inicial": 0,
    "etiqueta_final": 100
}

###

POST http://localhost:4000/lote_etiquetas/create
Content-Type: application/json

{
    "criacao":"12/11/2024",
    "semana_corte": 1,
    "semana_colheita": 13,
    "etiqueta_inicial": 0,
    "etiqueta_final": 100
}